apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sompob-api
  namespace: myorder-research-101
  labels:
    cloud.googleapis.com/location: asia-southeast1
  annotations:
    run.googleapis.com/binary-authorization: allUsers
spec:
  template:
    spec:
      containers:
      - image: asia-southeast1-docker.pkg.dev/myorder-research-101/mod-infrastructor-101/sompob-api:1.0 .
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://<USER>:<PASS>@cluster0.xfdupoe.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"