version: '3'
services:
  hero-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - hero-database
    environment:
      MONGODB_URI: "mongodb://hero-database:27017"
  hero-database:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"